name: Handling Pushes Requiring Submission
run-name: Handling A Push Requiring Submission By @${{ github.actor }}

# リモートのmainブランチへ、submitするノートブックがプッシュされた時に、自動でsubmitします。
# 何らかの理由でsubmitできなかった場合、ノートブックをsubmission待ちのリストに追加します。
# リストに追加されたノートブックは、手動のワークフローでsubmitするか、翌朝9時の自動submissionを待ちます。

on: 
  push:
    branches: [main]
    #paths: ['notebooks/models/*/*.ipynb'] # models/**.ipynb のような指定では、チェックポイントファイルを除外できない。

defaults:
  run:
    shell: bash

jobs:
  specify-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tanomu
        run: |
          echo "Fetching modified and added files via GitHub API..."
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.event.after }} \
            | jq -r '.files[] | select(.status == "added" or .status == "modified") | .filename'
      - name: Output pusher
        run: |
          echo "Pusher: ${{ github.actor }}"