name: Handling Pushes Requiring Submission
run-name: Handling A Push Requiring Submission By @${{ github.actor }}

# リモートのmainブランチへ、submitするノートブックがプッシュされた時に、自動でsubmitします。
# 何らかの理由でsubmitできなかった場合、ノートブックをsubmission待ちのリストに追加します。
# リストに追加されたノートブックは、手動のワークフローでsubmitするか、翌朝9時の自動submissionを待ちます。

on: 
  push:
    branches: [main]
    #paths: ['notebooks/models/*/*.ipynb'] # models/**.ipynb のような指定では、チェックポイントファイルを除外できない。

defaults:
  run:
    shell: bash

jobs:
  specify-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List added files
        run: |
          echo "Added files:"
          echo '${{ toJson(github.event.commits) }}' | jq -r '.[].added[]' || echo "No files added."
        continue-on-error: true
      - name: List modified files
        run: |
          echo "Modified files:"
          echo '${{ toJson(github.event.commits) }}' | jq -r '.[].modified[]' || echo "No files modified."
        continue-on-error: true
      - name: Output pusher
        run: |
          echo "Pusher: ${{ github.actor }}"