name: Kakikomi
on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  kakikomi:
    runs-on: ubuntu-latest
    permissions: write-all
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip
      - name: Configure git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: RENSHU
        env:
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        run: |
          result=$(python .scripts/workflows/sample3.py)
          git add .
          git commit -m "nekosanjou"
          git push origin main
          echo result